# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'sertiAppPrueba' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sertiAppPrueba

	pod 'Alamofire'

  target 'sertiAppPruebaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sertiAppPruebaUITests' do
    # Pods for testing
  end



end
